import { HttpStatus } from '@nestjs/common';
import { ApiExceptionWithKey } from './api-exception-with-key';

/**
 * Helper functions to create exceptions with messageKey and params
 */

export function badRequest(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.BAD_REQUEST, params);
}

export function notFound(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.NOT_FOUND, params);
}

export function conflict(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.CONFLICT, params);
}

export function forbidden(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.FORBIDDEN, params);
}

export function unauthorized(
  messageKey: string,
  params?: Record<string, string | number>,
) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.UNAUTHORIZED, params);
}

export function tooManyRequests(
  messageKey: string,
  params?: Record<string, string | number>,
) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.TOO_MANY_REQUESTS, params);
}

/**
 * Common message keys for reuse
 */
export const MessageKeys = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_REVOKED_OR_EXPIRED: 'TOKEN_REVOKED_OR_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  MISSING_OR_INVALID_AUTH_HEADER: 'MISSING_OR_INVALID_AUTH_HEADER',

  // OTP
  OTP_EXPIRED_OR_INVALID: 'OTP_EXPIRED_OR_INVALID',
  INVALID_OTP_CODE: 'INVALID_OTP_CODE',

  // Password
  PASSWORD_CONFIRMATION_MISMATCH: 'PASSWORD_CONFIRMATION_MISMATCH',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',

  // Admin
  ADMIN_ACCOUNT_INACTIVE: 'ADMIN_ACCOUNT_INACTIVE',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Auth Success
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  USER_REGISTERED_SUCCESS: 'USER_REGISTERED_SUCCESS',
  TOKEN_REFRESHED_SUCCESS: 'TOKEN_REFRESHED_SUCCESS',
  OTP_VERIFIED_SUCCESS: 'OTP_VERIFIED_SUCCESS',
  OTP_VERIFIED_FORGOT_PASSWORD_SUCCESS: 'OTP_VERIFIED_FORGOT_PASSWORD_SUCCESS',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',
  PASSWORD_CHANGED_SUCCESS: 'PASSWORD_CHANGED_SUCCESS',
  SEARCH_HISTORY_DELETED_SUCCESS: 'SEARCH_HISTORY_DELETED_SUCCESS',
  SITE_HISTORY_DELETED_SUCCESS: 'SITE_HISTORY_DELETED_SUCCESS',

  // Not found
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  SITE_REVIEW_NOT_FOUND: 'SITE_REVIEW_NOT_FOUND',
  SITE_REVIEW_NOT_FOUND_AFTER_UPDATE: 'SITE_REVIEW_NOT_FOUND_AFTER_UPDATE',
  SITE_REVIEW_NOT_FOUND_AFTER_CREATE: 'SITE_REVIEW_NOT_FOUND_AFTER_CREATE',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_NOT_FOUND_AFTER_CREATE: 'POST_NOT_FOUND_AFTER_CREATE',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  PARTNER_ROLE_NOT_FOUND: 'PARTNER_ROLE_NOT_FOUND',
  PARTNER_USER_NOT_FOUND: 'PARTNER_USER_NOT_FOUND',
  INQUIRY_NOT_FOUND: 'INQUIRY_NOT_FOUND',
  INQUIRY_NOT_FOUND_AFTER_UPDATE: 'INQUIRY_NOT_FOUND_AFTER_UPDATE',
  ONLY_PENDING_INQUIRIES_CAN_BE_UPDATED: 'ONLY_PENDING_INQUIRIES_CAN_BE_UPDATED',
  INVALID_INQUIRY_STATUS_FOR_ADMIN: 'INVALID_INQUIRY_STATUS_FOR_ADMIN',
  SCAM_REPORT_NOT_FOUND: 'SCAM_REPORT_NOT_FOUND',
  SCAM_REPORT_NOT_FOUND_AFTER_UPDATE: 'SCAM_REPORT_NOT_FOUND_AFTER_UPDATE',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  POST_NOT_FOUND_AFTER_UPDATE: 'POST_NOT_FOUND_AFTER_UPDATE',
  SITE_NOT_FOUND_AFTER_UPDATE: 'SITE_NOT_FOUND_AFTER_UPDATE',
  SITE_NOT_FOUND_AFTER_CREATE: 'SITE_NOT_FOUND_AFTER_CREATE',
  SITE_NOT_FOUND_AFTER_RESTORE: 'SITE_NOT_FOUND_AFTER_RESTORE',
  CATEGORY_NOT_FOUND_AFTER_UPDATE: 'CATEGORY_NOT_FOUND_AFTER_UPDATE',
  CATEGORY_NOT_FOUND_AFTER_RESTORE: 'CATEGORY_NOT_FOUND_AFTER_RESTORE',
  CATEGORY_NOT_DELETED: 'CATEGORY_NOT_DELETED',
  DOMAIN_NOT_FOUND: 'DOMAIN_NOT_FOUND',
  DOMAIN_NOT_FOUND_AFTER_UPDATE: 'DOMAIN_NOT_FOUND_AFTER_UPDATE',
  BADGE_NOT_FOUND: 'BADGE_NOT_FOUND',
  BADGE_NOT_FOUND_AFTER_UPDATE: 'BADGE_NOT_FOUND_AFTER_UPDATE',
  BADGE_NAME_ALREADY_EXISTS: 'BADGE_NAME_ALREADY_EXISTS',
  POINT_REQUIRED_FOR_USER_BADGES: 'POINT_REQUIRED_FOR_USER_BADGES',
  BADGE_ALREADY_DELETED: 'BADGE_ALREADY_DELETED',
  BADGE_IS_NOT_DELETED: 'BADGE_IS_NOT_DELETED',
  CANNOT_DELETE_BADGE_ASSIGNED_TO_USERS: 'CANNOT_DELETE_BADGE_ASSIGNED_TO_USERS',
  OTP_REQUEST_NOT_FOUND: 'OTP_REQUEST_NOT_FOUND',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  COMMENT_NOT_FOUND_AFTER_CREATE: 'COMMENT_NOT_FOUND_AFTER_CREATE',
  COMMENT_NOT_FOUND_AFTER_UPDATE: 'COMMENT_NOT_FOUND_AFTER_UPDATE',
  COMMENT_IMAGE_NOT_FOUND: 'COMMENT_IMAGE_NOT_FOUND',
  CAN_ONLY_UPDATE_OWN_COMMENTS: 'CAN_ONLY_UPDATE_OWN_COMMENTS',
  PARENT_COMMENT_NOT_FOUND: 'PARENT_COMMENT_NOT_FOUND',
  PARENT_COMMENT_NOT_FOUND_OR_INVALID: 'PARENT_COMMENT_NOT_FOUND_OR_INVALID',
  REACTION_NOT_FOUND: 'REACTION_NOT_FOUND',
  REACTION_NOT_FOUND_AFTER_UPDATE: 'REACTION_NOT_FOUND_AFTER_UPDATE',
  MAX_IMAGES_PER_COMMENT_EXCEEDED: 'MAX_IMAGES_PER_COMMENT_EXCEEDED',
  EXCHANGE_NOT_FOUND: 'EXCHANGE_NOT_FOUND',
  EXCHANGE_NOT_FOUND_AFTER_UPDATE: 'EXCHANGE_NOT_FOUND_AFTER_UPDATE',
  EXCHANGE_DOES_NOT_BELONG_TO_SITE: 'EXCHANGE_DOES_NOT_BELONG_TO_SITE',
  NO_PERMISSION_TO_VIEW_EXCHANGES: 'NO_PERMISSION_TO_VIEW_EXCHANGES',
  NO_PERMISSION_TO_REJECT_EXCHANGES: 'NO_PERMISSION_TO_REJECT_EXCHANGES',
  NO_PERMISSION_TO_APPROVE_EXCHANGES: 'NO_PERMISSION_TO_APPROVE_EXCHANGES',
  NO_PERMISSION_TO_MOVE_EXCHANGES_TO_PROCESSING:
    'NO_PERMISSION_TO_MOVE_EXCHANGES_TO_PROCESSING',
  ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_APPROVED:
    'ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_APPROVED',
  ONLY_PENDING_EXCHANGES_CAN_BE_MOVED_TO_PROCESSING:
    'ONLY_PENDING_EXCHANGES_CAN_BE_MOVED_TO_PROCESSING',
  ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_REJECTED:
    'ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_REJECTED',
  ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_CANCELLED:
    'ONLY_PENDING_OR_PROCESSING_EXCHANGES_CAN_BE_CANCELLED',
  CAN_ONLY_CANCEL_OWN_EXCHANGES: 'CAN_ONLY_CANCEL_OWN_EXCHANGES',
  NOT_AUTHORIZED_TO_VIEW_EXCHANGE: 'NOT_AUTHORIZED_TO_VIEW_EXCHANGE',
  USER_PROFILE_NOT_FOUND: 'USER_PROFILE_NOT_FOUND',
  REDEMPTION_NOT_FOUND: 'REDEMPTION_NOT_FOUND',
  REDEMPTION_NOT_FOUND_AFTER_UPDATE: 'REDEMPTION_NOT_FOUND_AFTER_UPDATE',
  NOT_AUTHORIZED_TO_VIEW_REDEMPTION: 'NOT_AUTHORIZED_TO_VIEW_REDEMPTION',
  ONLY_PENDING_REDEMPTIONS_CAN_BE_APPROVED: 'ONLY_PENDING_REDEMPTIONS_CAN_BE_APPROVED',
  ONLY_PENDING_REDEMPTIONS_CAN_BE_REJECTED: 'ONLY_PENDING_REDEMPTIONS_CAN_BE_REJECTED',
  ONLY_PENDING_REDEMPTIONS_CAN_BE_CANCELLED: 'ONLY_PENDING_REDEMPTIONS_CAN_BE_CANCELLED',
  GIFTICON_NOT_FOUND: 'GIFTICON_NOT_FOUND',
  GIFTICON_NOT_FOUND_AFTER_UPDATE: 'GIFTICON_NOT_FOUND_AFTER_UPDATE',
  GIFTICON_NOT_AVAILABLE_FOR_REDEMPTION: 'GIFTICON_NOT_AVAILABLE_FOR_REDEMPTION',
  GIFTICON_NOT_STARTED_YET: 'GIFTICON_NOT_STARTED_YET',
  GIFTICON_EXPIRED: 'GIFTICON_EXPIRED',
  GIFTICON_HAS_NOT_STARTED: 'GIFTICON_HAS_NOT_STARTED',
  GIFTICON_HAS_EXPIRED: 'GIFTICON_HAS_EXPIRED',
  CAN_ONLY_CANCEL_OWN_REDEMPTIONS: 'CAN_ONLY_CANCEL_OWN_REDEMPTIONS',
  PARTNER_REQUEST_NOT_FOUND: 'PARTNER_REQUEST_NOT_FOUND',
  PARTNER_REQUEST_NOT_FOUND_AFTER_CREATE: 'PARTNER_REQUEST_NOT_FOUND_AFTER_CREATE',
  PARTNER_REQUEST_NOT_FOUND_AFTER_UPDATE: 'PARTNER_REQUEST_NOT_FOUND_AFTER_UPDATE',
  PARTNER_REQUEST_NOT_FOUND_AFTER_APPROVAL: 'PARTNER_REQUEST_NOT_FOUND_AFTER_APPROVAL',
  PARTNER_REQUEST_NOT_FOUND_AFTER_REJECTION: 'PARTNER_REQUEST_NOT_FOUND_AFTER_REJECTION',
  PARTNER_REQUEST_ALREADY_PROCESSED: 'PARTNER_REQUEST_ALREADY_PROCESSED',
  USER_ALREADY_HAS_PARTNER_ROLE: 'USER_ALREADY_HAS_PARTNER_ROLE',
  PENDING_PARTNER_REQUEST_EXISTS: 'PENDING_PARTNER_REQUEST_EXISTS',
  APPROVED_PARTNER_REQUEST_EXISTS: 'APPROVED_PARTNER_REQUEST_EXISTS',
  PARTNER_REQUEST_PENDING_EXISTS: 'PARTNER_REQUEST_PENDING_EXISTS',
  PARTNER_REQUEST_APPROVED_EXISTS: 'PARTNER_REQUEST_APPROVED_EXISTS',
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_NOT_FOUND_AFTER_CREATE: 'APPLICATION_NOT_FOUND_AFTER_CREATE',
  APPLICATION_NOT_FOUND_AFTER_APPROVAL: 'APPLICATION_NOT_FOUND_AFTER_APPROVAL',
  APPLICATION_NOT_FOUND_AFTER_REJECTION: 'APPLICATION_NOT_FOUND_AFTER_REJECTION',
  APPLICATION_ALREADY_PROCESSED: 'APPLICATION_ALREADY_PROCESSED',
  USER_ALREADY_MANAGER_FOR_SITE: 'USER_ALREADY_MANAGER_FOR_SITE',
  PENDING_APPLICATION_EXISTS: 'PENDING_APPLICATION_EXISTS',
  APPROVED_APPLICATION_EXISTS: 'APPROVED_APPLICATION_EXISTS',
  SITE_REVIEW_ALREADY_APPROVED: 'SITE_REVIEW_ALREADY_APPROVED',
  SITE_REVIEW_NOT_APPROVED: 'SITE_REVIEW_NOT_APPROVED',
  MIN_EXCHANGE_AMOUNT: 'MIN_EXCHANGE_AMOUNT',
  EXCHANGE_AMOUNT_NOT_MULTIPLE: 'EXCHANGE_AMOUNT_NOT_MULTIPLE',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  TIER_NOT_FOUND_AFTER_UPDATE: 'TIER_NOT_FOUND_AFTER_UPDATE',
  TIER_IS_ALREADY_DELETED: 'TIER_IS_ALREADY_DELETED',
  TIER_IS_NOT_DELETED: 'TIER_IS_NOT_DELETED',
  CANNOT_DELETE_TIER_IN_USE: 'CANNOT_DELETE_TIER_IN_USE',
  TIER_NAME_ALREADY_EXISTS: 'TIER_NAME_ALREADY_EXISTS',
  MESSAGE_EXCEEDS_LIMIT: 'MESSAGE_EXCEEDS_LIMIT',
  ALREADY_CHECKED_IN_TODAY: 'ALREADY_CHECKED_IN_TODAY',
  SCAM_REPORT_NOT_PUBLISHED: 'SCAM_REPORT_NOT_PUBLISHED',
  NO_PERMISSION_TO_DELETE_SCAM_REPORT: 'NO_PERMISSION_TO_DELETE_SCAM_REPORT',
  ONLY_PENDING_SCAM_REPORTS_CAN_BE_DELETED: 'ONLY_PENDING_SCAM_REPORTS_CAN_BE_DELETED',
  PARENT_COMMENT_NOT_FOUND_OR_DELETED: 'PARENT_COMMENT_NOT_FOUND_OR_DELETED',
  PARENT_COMMENT_DOES_NOT_BELONG_TO_REPORT: 'PARENT_COMMENT_DOES_NOT_BELONG_TO_REPORT',
  SITE_REVIEW_ALREADY_EXISTS: 'SITE_REVIEW_ALREADY_EXISTS',
  SITE_ID_REQUIRED: 'SITE_ID_REQUIRED',
  SITE_MANAGER_NOT_FOUND_AFTER_UPDATE: 'SITE_MANAGER_NOT_FOUND_AFTER_UPDATE',
  SITE_MANAGER_APPLICATION_NOT_FOUND_AFTER_UPDATE: 'SITE_MANAGER_APPLICATION_NOT_FOUND_AFTER_UPDATE',
  SITE_CATEGORY_NOT_FOUND_AFTER_UPDATE: 'SITE_CATEGORY_NOT_FOUND_AFTER_UPDATE',
  POST_CATEGORY_NOT_FOUND_AFTER_UPDATE: 'POST_CATEGORY_NOT_FOUND_AFTER_UPDATE',
  POST_CATEGORY_NOT_FOUND_AFTER_RESTORE: 'POST_CATEGORY_NOT_FOUND_AFTER_RESTORE',
  POST_COMMENT_NOT_FOUND_AFTER_UPDATE: 'POST_COMMENT_NOT_FOUND_AFTER_UPDATE',
  POST_COMMENT_NOT_FOUND_AFTER_CREATE: 'POST_COMMENT_NOT_FOUND_AFTER_CREATE',
  POST_COMMENT_REACTION_NOT_FOUND_AFTER_UPDATE: 'POST_COMMENT_REACTION_NOT_FOUND_AFTER_UPDATE',
  POST_REACTION_NOT_FOUND_AFTER_UPDATE: 'POST_REACTION_NOT_FOUND_AFTER_UPDATE',
  SITE_REVIEW_COMMENT_NOT_FOUND_AFTER_UPDATE: 'SITE_REVIEW_COMMENT_NOT_FOUND_AFTER_UPDATE',
  SITE_REVIEW_REACTION_NOT_FOUND_AFTER_UPDATE: 'SITE_REVIEW_REACTION_NOT_FOUND_AFTER_UPDATE',
  POCA_EVENT_NOT_FOUND_AFTER_UPDATE: 'POCA_EVENT_NOT_FOUND_AFTER_UPDATE',
  POCA_EVENT_NOT_FOUND_AFTER_CREATE: 'POCA_EVENT_NOT_FOUND_AFTER_CREATE',
  GIFTCON_REDEMPTION_NOT_FOUND_AFTER_UPDATE: 'GIFTCON_REDEMPTION_NOT_FOUND_AFTER_UPDATE',
  POINT_EXCHANGE_NOT_FOUND_AFTER_UPDATE: 'POINT_EXCHANGE_NOT_FOUND_AFTER_UPDATE',
  ATTENDANCE_STATISTIC_REQUIRED_FIELDS: 'ATTENDANCE_STATISTIC_REQUIRED_FIELDS',
  SITE_BADGE_REQUEST_NOT_FOUND: 'SITE_BADGE_REQUEST_NOT_FOUND',
  SITE_BADGE_REQUEST_NOT_FOUND_AFTER_CREATE: 'SITE_BADGE_REQUEST_NOT_FOUND_AFTER_CREATE',
  SITE_BADGE_REQUEST_NOT_FOUND_AFTER_UPDATE: 'SITE_BADGE_REQUEST_NOT_FOUND_AFTER_UPDATE',
  USER_BADGE_REQUEST_NOT_FOUND: 'USER_BADGE_REQUEST_NOT_FOUND',
  USER_BADGE_REQUEST_NOT_FOUND_AFTER_CREATE: 'USER_BADGE_REQUEST_NOT_FOUND_AFTER_CREATE',
  USER_BADGE_REQUEST_NOT_FOUND_AFTER_UPDATE: 'USER_BADGE_REQUEST_NOT_FOUND_AFTER_UPDATE',
  PENDING_BADGE_REQUEST_EXISTS: 'PENDING_BADGE_REQUEST_EXISTS',
  BADGE_REQUEST_ALREADY_PROCESSED: 'BADGE_REQUEST_ALREADY_PROCESSED',
  CAN_ONLY_CANCEL_PENDING_BADGE_REQUEST: 'CAN_ONLY_CANCEL_PENDING_BADGE_REQUEST',

  // Conflict
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  POST_TITLE_ALREADY_EXISTS: 'POST_TITLE_ALREADY_EXISTS',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  SITE_NAME_ALREADY_EXISTS: 'SITE_NAME_ALREADY_EXISTS',
  SITE_SLUG_ALREADY_EXISTS: 'SITE_SLUG_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  START_DATE_MUST_BE_BEFORE_END_DATE: 'START_DATE_MUST_BE_BEFORE_END_DATE',
  DOMAIN_ALREADY_EXISTS: 'DOMAIN_ALREADY_EXISTS',
  BADGE_ALREADY_ASSIGNED_TO_USER: 'BADGE_ALREADY_ASSIGNED_TO_USER',
  BADGE_ALREADY_ASSIGNED_TO_SITE: 'BADGE_ALREADY_ASSIGNED_TO_SITE',

  // File
  FILE_REQUIRED: 'FILE_REQUIRED',
  FILE_SIZE_EXCEEDS_LIMIT: 'FILE_SIZE_EXCEEDS_LIMIT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  IMAGE_FILE_SIZE_EXCEEDS_LIMIT: 'IMAGE_FILE_SIZE_EXCEEDS_LIMIT',
  INVALID_IMAGE_FILE_TYPE: 'INVALID_IMAGE_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  MAX_BANNERS_EXCEEDED: 'MAX_BANNERS_EXCEEDED',
  MAX_FILES_EXCEEDED: 'MAX_FILES_EXCEEDED',
  BANNER_MUST_HAVE_IMAGE_OR_LINK: 'BANNER_MUST_HAVE_IMAGE_OR_LINK',
  NO_PERMISSION_TO_CREATE_EVENTS: 'NO_PERMISSION_TO_CREATE_EVENTS',
  NO_PERMISSION_TO_UPDATE_EVENTS: 'NO_PERMISSION_TO_UPDATE_EVENTS',
  NO_PERMISSION_TO_DELETE_EVENTS: 'NO_PERMISSION_TO_DELETE_EVENTS',
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_FOUND_AFTER_CREATE: 'EVENT_NOT_FOUND_AFTER_CREATE',
  EVENT_NOT_FOUND_AFTER_UPDATE: 'EVENT_NOT_FOUND_AFTER_UPDATE',
  BANNER_DOES_NOT_BELONG_TO_EVENT: 'BANNER_DOES_NOT_BELONG_TO_EVENT',

  // User
  USER_ACCOUNT_INACTIVE: 'USER_ACCOUNT_INACTIVE',
  USER_NOT_FOUND_OR_INACTIVE: 'USER_NOT_FOUND_OR_INACTIVE',
  USER_DOES_NOT_HAVE_PARTNER_ROLE: 'USER_DOES_NOT_HAVE_PARTNER_ROLE',
  BADGE_NOT_ASSIGNED_TO_USER: 'BADGE_NOT_ASSIGNED_TO_USER',
  BADGE_NOT_AVAILABLE: 'BADGE_NOT_AVAILABLE',
  BADGE_WRONG_TYPE: 'BADGE_WRONG_TYPE',
  TOKEN_REQUIRED_FOR_PHONE_UPDATE: 'TOKEN_REQUIRED_FOR_PHONE_UPDATE',
  INVALID_PHONE_NUMBER_FORMAT: 'INVALID_PHONE_NUMBER_FORMAT',
  TOKEN_EXPIRED_PLEASE_VERIFY_OTP: 'TOKEN_EXPIRED_PLEASE_VERIFY_OTP',
  TOKEN_DOES_NOT_MATCH_PHONE: 'TOKEN_DOES_NOT_MATCH_PHONE',

  // Post
  CANNOT_CREATE_POST_WITH_ADMIN_ONLY_CATEGORY:
    'CANNOT_CREATE_POST_WITH_ADMIN_ONLY_CATEGORY',
  CANNOT_CREATE_POST_WITH_SPECIAL_KEY_CATEGORY:
    'CANNOT_CREATE_POST_WITH_SPECIAL_KEY_CATEGORY',
  CANNOT_UPDATE_POST_TO_SPECIAL_KEY_CATEGORY:
    'CANNOT_UPDATE_POST_TO_SPECIAL_KEY_CATEGORY',
  CAN_ONLY_UPDATE_OWN_POSTS: 'CAN_ONLY_UPDATE_OWN_POSTS',
  CAN_ONLY_EDIT_POSTS_WITHIN_ONE_HOUR: 'CAN_ONLY_EDIT_POSTS_WITHIN_ONE_HOUR',
  CAN_ONLY_DELETE_OWN_POSTS: 'CAN_ONLY_DELETE_OWN_POSTS',
  CAN_ONLY_DELETE_POSTS_WITHIN_ONE_HOUR: 'CAN_ONLY_DELETE_POSTS_WITHIN_ONE_HOUR',
  CAN_ONLY_DELETE_OWN_REACTIONS: 'CAN_ONLY_DELETE_OWN_REACTIONS',
  CAN_ONLY_UPDATE_OWN_REVIEWS: 'CAN_ONLY_UPDATE_OWN_REVIEWS',
  CAN_ONLY_UPDATE_REVIEWS_WITHIN_TWO_HOURS: 'CAN_ONLY_UPDATE_REVIEWS_WITHIN_TWO_HOURS',
  CAN_ONLY_DELETE_OWN_REVIEWS: 'CAN_ONLY_DELETE_OWN_REVIEWS',
  CAN_ONLY_COMMENT_ON_PUBLISHED_REVIEWS: 'CAN_ONLY_COMMENT_ON_PUBLISHED_REVIEWS',
  CAN_ONLY_COMMENT_ON_PUBLISHED_POSTS: 'CAN_ONLY_COMMENT_ON_PUBLISHED_POSTS',
  CAN_ONLY_VIEW_COMMENTS_ON_PUBLISHED_REVIEWS: 'CAN_ONLY_VIEW_COMMENTS_ON_PUBLISHED_REVIEWS',

  // Category
  INVALID_SPECIAL_KEY: 'INVALID_SPECIAL_KEY',

  // Site
  NO_PERMISSION_TO_EDIT_SITE: 'NO_PERMISSION_TO_EDIT_SITE',
  SITE_MUST_BE_VERIFIED_BEFORE_UPDATE: 'SITE_MUST_BE_VERIFIED_BEFORE_UPDATE',
  SITE_NOT_AVAILABLE_FOR_VIEWING: 'SITE_NOT_AVAILABLE_FOR_VIEWING',
  CATEGORY_IS_NOT_DELETED: 'CATEGORY_IS_NOT_DELETED',
  CATEGORY_IS_ALREADY_DELETED: 'CATEGORY_IS_ALREADY_DELETED',
  CANNOT_DELETE_CATEGORY_IN_USE: 'CANNOT_DELETE_CATEGORY_IN_USE',
  SITE_IS_NOT_DELETED: 'SITE_IS_NOT_DELETED',

  // Scam Report
  SCAM_REPORT_ALREADY_PROCESSED: 'SCAM_REPORT_ALREADY_PROCESSED',
  CAN_ONLY_UPDATE_OWN_SCAM_REPORTS: 'CAN_ONLY_UPDATE_OWN_SCAM_REPORTS',
  CAN_ONLY_UPDATE_PENDING_SCAM_REPORTS: 'CAN_ONLY_UPDATE_PENDING_SCAM_REPORTS',
  CAN_ONLY_DELETE_PENDING_SCAM_REPORTS: 'CAN_ONLY_DELETE_PENDING_SCAM_REPORTS',
  SCAM_REPORT_IS_NOT_PUBLISHED: 'SCAM_REPORT_IS_NOT_PUBLISHED',
  SCAM_REPORT_NOT_AVAILABLE_FOR_VIEWING: 'SCAM_REPORT_NOT_AVAILABLE_FOR_VIEWING',
  CAN_ONLY_COMMENT_ON_PUBLISHED_SCAM_REPORTS:
    'CAN_ONLY_COMMENT_ON_PUBLISHED_SCAM_REPORTS',
  CAN_ONLY_DELETE_OWN_COMMENTS: 'CAN_ONLY_DELETE_OWN_COMMENTS',

  // OTP
  OTP_NOT_FOUND: 'OTP_NOT_FOUND',
  OTP_HAS_EXPIRED: 'OTP_HAS_EXPIRED',
  OTP_ALREADY_SENT: 'OTP_ALREADY_SENT',

  // Success Messages
  PROFILE_UPDATED_SUCCESS: 'PROFILE_UPDATED_SUCCESS',
  ADMIN_CREATED_SUCCESS: 'ADMIN_CREATED_SUCCESS',
  ADMIN_RETRIEVED_SUCCESS: 'ADMIN_RETRIEVED_SUCCESS',
  SITE_CREATED_SUCCESS: 'SITE_CREATED_SUCCESS',
  SITE_DELETED_SUCCESS: 'SITE_DELETED_SUCCESS',
  SITE_RESTORED_SUCCESS: 'SITE_RESTORED_SUCCESS',
  DOMAIN_ADDED_SUCCESS: 'DOMAIN_ADDED_SUCCESS',
  SITE_BADGE_ASSIGNED_SUCCESS: 'SITE_BADGE_ASSIGNED_SUCCESS',
  SITE_BADGE_REMOVED_SUCCESS: 'SITE_BADGE_REMOVED_SUCCESS',
  DOMAIN_UPDATED_SUCCESS: 'DOMAIN_UPDATED_SUCCESS',
  DOMAIN_DELETED_SUCCESS: 'DOMAIN_DELETED_SUCCESS',
  SITE_REVIEW_DELETED_SUCCESS: 'SITE_REVIEW_DELETED_SUCCESS',
  SITE_REVIEW_CREATED_SUCCESS: 'SITE_REVIEW_CREATED_SUCCESS',
  SITE_REVIEW_UPDATED_SUCCESS: 'SITE_REVIEW_UPDATED_SUCCESS',
  SITE_REVIEW_STATISTICS_RETRIEVED_SUCCESS: 'SITE_REVIEW_STATISTICS_RETRIEVED_SUCCESS',
  SITE_REVIEW_APPROVED_SUCCESS: 'SITE_REVIEW_APPROVED_SUCCESS',
  SITE_REVIEW_REJECTED_SUCCESS: 'SITE_REVIEW_REJECTED_SUCCESS',
  REACTION_UPDATED_SUCCESS: 'REACTION_UPDATED_SUCCESS',
  COMMENT_DELETED_SUCCESS: 'COMMENT_DELETED_SUCCESS',
  BADGE_DELETED_SUCCESS: 'BADGE_DELETED_SUCCESS',
  BADGE_RESTORED_SUCCESS: 'BADGE_RESTORED_SUCCESS',
  BADGE_ASSIGNED_SUCCESS: 'BADGE_ASSIGNED_SUCCESS',
  BADGE_REMOVED_SUCCESS: 'BADGE_REMOVED_SUCCESS',
  TIER_CREATED_SUCCESS: 'TIER_CREATED_SUCCESS',
  TIER_UPDATED_SUCCESS: 'TIER_UPDATED_SUCCESS',
  TIER_DELETED_SUCCESS: 'TIER_DELETED_SUCCESS',
  TIER_RESTORED_SUCCESS: 'TIER_RESTORED_SUCCESS',
  CATEGORY_CREATED_SUCCESS: 'CATEGORY_CREATED_SUCCESS',
  CATEGORY_UPDATED_SUCCESS: 'CATEGORY_UPDATED_SUCCESS',
  CATEGORY_DELETED_SUCCESS: 'CATEGORY_DELETED_SUCCESS',
  CATEGORY_RESTORED_SUCCESS: 'CATEGORY_RESTORED_SUCCESS',
  POST_CREATED_SUCCESS: 'POST_CREATED_SUCCESS',
  POST_UPDATED_SUCCESS: 'POST_UPDATED_SUCCESS',
  POST_DELETED_SUCCESS: 'POST_DELETED_SUCCESS',
  REACTION_ADDED_SUCCESS: 'REACTION_ADDED_SUCCESS',
  REACTION_DELETED_SUCCESS: 'REACTION_DELETED_SUCCESS',
  COMMENT_ADDED_SUCCESS: 'COMMENT_ADDED_SUCCESS',
  COMMENT_UPDATED_SUCCESS: 'COMMENT_UPDATED_SUCCESS',
  USER_DELETED_SUCCESS: 'USER_DELETED_SUCCESS',
  OTP_SENT_SUCCESS: 'OTP_SENT_SUCCESS',
  OTP_SENT_TO_PHONE_SUCCESS: 'OTP_SENT_TO_PHONE_SUCCESS',
  OTP_GENERATED_TO_PHONE_SUCCESS: 'OTP_GENERATED_TO_PHONE_SUCCESS',
  SCAM_REPORT_CREATED_SUCCESS: 'SCAM_REPORT_CREATED_SUCCESS',
  SCAM_REPORT_UPDATED_SUCCESS: 'SCAM_REPORT_UPDATED_SUCCESS',
  SCAM_REPORT_DELETED_SUCCESS: 'SCAM_REPORT_DELETED_SUCCESS',
  SCAM_REPORT_APPROVED_SUCCESS: 'SCAM_REPORT_APPROVED_SUCCESS',
  SCAM_REPORT_REJECTED_SUCCESS: 'SCAM_REPORT_REJECTED_SUCCESS',
  GIFTCON_DELETED_SUCCESS: 'GIFTCON_DELETED_SUCCESS',
  EVENT_DELETED_SUCCESS: 'EVENT_DELETED_SUCCESS',
  ATTENDANCE_CHECKED_SUCCESS: 'ATTENDANCE_CHECKED_SUCCESS',
  OTP_GENERATED_SUCCESS: 'OTP_GENERATED_SUCCESS',
  OTP_SENT_IF_EMAIL_EXISTS: 'OTP_SENT_IF_EMAIL_EXISTS',
  USER_IP_BLOCKED_SUCCESS: 'USER_IP_BLOCKED_SUCCESS',
  USER_IP_UNBLOCKED_SUCCESS: 'USER_IP_UNBLOCKED_SUCCESS',
  GLOBAL_IP_BLOCKED_SUCCESS: 'GLOBAL_IP_BLOCKED_SUCCESS',
  GLOBAL_IP_UNBLOCKED_SUCCESS: 'GLOBAL_IP_UNBLOCKED_SUCCESS',
  IP_SYNC_TRIGGERED_SUCCESS: 'IP_SYNC_TRIGGERED_SUCCESS',
  FUNCTION_NOT_AVAILABLE: 'FUNCTION_NOT_AVAILABLE',
  BADGEID_TOO_MANY: 'BADGEID_TOO_MANY',
  BADGEID_REQUIRED: 'BADGEID_REQUIRED',
} as const;
