import { HttpStatus } from '@nestjs/common';
import { ApiExceptionWithKey } from './api-exception-with-key';

/**
 * Helper functions to create exceptions with messageKey and params
 */

export function badRequest(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.BAD_REQUEST, params);
}

export function notFound(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.NOT_FOUND, params);
}

export function conflict(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.CONFLICT, params);
}

export function forbidden(messageKey: string, params?: Record<string, string | number>) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.FORBIDDEN, params);
}

export function unauthorized(
  messageKey: string,
  params?: Record<string, string | number>,
) {
  return new ApiExceptionWithKey(messageKey, HttpStatus.UNAUTHORIZED, params);
}

/**
 * Common message keys for reuse
 */
export const MessageKeys = {
  // Generic
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
  TOKEN_REVOKED_OR_EXPIRED: 'TOKEN_REVOKED_OR_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  MISSING_OR_INVALID_AUTH_HEADER: 'MISSING_OR_INVALID_AUTH_HEADER',

  // OTP
  OTP_EXPIRED_OR_INVALID: 'OTP_EXPIRED_OR_INVALID',
  INVALID_OTP_CODE: 'INVALID_OTP_CODE',

  // Password
  PASSWORD_CONFIRMATION_MISMATCH: 'PASSWORD_CONFIRMATION_MISMATCH',
  CURRENT_PASSWORD_INCORRECT: 'CURRENT_PASSWORD_INCORRECT',

  // Admin
  ADMIN_ACCOUNT_INACTIVE: 'ADMIN_ACCOUNT_INACTIVE',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',

  // Auth Success
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  USER_REGISTERED_SUCCESS: 'USER_REGISTERED_SUCCESS',
  TOKEN_REFRESHED_SUCCESS: 'TOKEN_REFRESHED_SUCCESS',
  OTP_VERIFIED_SUCCESS: 'OTP_VERIFIED_SUCCESS',
  PASSWORD_RESET_SUCCESS: 'PASSWORD_RESET_SUCCESS',

  // Not found
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  SITE_NOT_FOUND: 'SITE_NOT_FOUND',
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  PARTNER_ROLE_NOT_FOUND: 'PARTNER_ROLE_NOT_FOUND',
  INQUIRY_NOT_FOUND: 'INQUIRY_NOT_FOUND',
  SCAM_REPORT_NOT_FOUND: 'SCAM_REPORT_NOT_FOUND',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  POST_NOT_FOUND_AFTER_UPDATE: 'POST_NOT_FOUND_AFTER_UPDATE',
  SITE_NOT_FOUND_AFTER_UPDATE: 'SITE_NOT_FOUND_AFTER_UPDATE',
  CATEGORY_NOT_FOUND_AFTER_UPDATE: 'CATEGORY_NOT_FOUND_AFTER_UPDATE',

  // Conflict
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  POST_TITLE_ALREADY_EXISTS: 'POST_TITLE_ALREADY_EXISTS',
  CATEGORY_NAME_ALREADY_EXISTS: 'CATEGORY_NAME_ALREADY_EXISTS',
  SITE_NAME_ALREADY_EXISTS: 'SITE_NAME_ALREADY_EXISTS',
  SITE_SLUG_ALREADY_EXISTS: 'SITE_SLUG_ALREADY_EXISTS',

  // File
  FILE_SIZE_EXCEEDS_LIMIT: 'FILE_SIZE_EXCEEDS_LIMIT',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // User
  USER_ACCOUNT_INACTIVE: 'USER_ACCOUNT_INACTIVE',
  USER_DOES_NOT_HAVE_PARTNER_ROLE: 'USER_DOES_NOT_HAVE_PARTNER_ROLE',
  BADGE_NOT_ASSIGNED_TO_USER: 'BADGE_NOT_ASSIGNED_TO_USER',
  TOKEN_REQUIRED_FOR_PHONE_UPDATE: 'TOKEN_REQUIRED_FOR_PHONE_UPDATE',

  // Post
  CANNOT_CREATE_POST_WITH_ADMIN_ONLY_CATEGORY:
    'CANNOT_CREATE_POST_WITH_ADMIN_ONLY_CATEGORY',
  CANNOT_CREATE_POST_WITH_SPECIAL_KEY_CATEGORY:
    'CANNOT_CREATE_POST_WITH_SPECIAL_KEY_CATEGORY',
  CANNOT_UPDATE_POST_TO_SPECIAL_KEY_CATEGORY:
    'CANNOT_UPDATE_POST_TO_SPECIAL_KEY_CATEGORY',
  CAN_ONLY_UPDATE_OWN_POSTS: 'CAN_ONLY_UPDATE_OWN_POSTS',
  CAN_ONLY_EDIT_POSTS_WITHIN_ONE_HOUR: 'CAN_ONLY_EDIT_POSTS_WITHIN_ONE_HOUR',

  // Category
  INVALID_SPECIAL_KEY: 'INVALID_SPECIAL_KEY',

  // Site
  NO_PERMISSION_TO_EDIT_SITE: 'NO_PERMISSION_TO_EDIT_SITE',

  // Scam Report
  SCAM_REPORT_ALREADY_PROCESSED: 'SCAM_REPORT_ALREADY_PROCESSED',
  CAN_ONLY_UPDATE_OWN_SCAM_REPORTS: 'CAN_ONLY_UPDATE_OWN_SCAM_REPORTS',

  // Success Messages
  PROFILE_UPDATED_SUCCESS: 'PROFILE_UPDATED_SUCCESS',
  ADMIN_CREATED_SUCCESS: 'ADMIN_CREATED_SUCCESS',
  ADMIN_RETRIEVED_SUCCESS: 'ADMIN_RETRIEVED_SUCCESS',
  SITE_CREATED_SUCCESS: 'SITE_CREATED_SUCCESS',
  SITE_DELETED_SUCCESS: 'SITE_DELETED_SUCCESS',
  SITE_RESTORED_SUCCESS: 'SITE_RESTORED_SUCCESS',
  DOMAIN_ADDED_SUCCESS: 'DOMAIN_ADDED_SUCCESS',
  SITE_BADGE_ASSIGNED_SUCCESS: 'SITE_BADGE_ASSIGNED_SUCCESS',
  SITE_BADGE_REMOVED_SUCCESS: 'SITE_BADGE_REMOVED_SUCCESS',
  DOMAIN_UPDATED_SUCCESS: 'DOMAIN_UPDATED_SUCCESS',
  DOMAIN_DELETED_SUCCESS: 'DOMAIN_DELETED_SUCCESS',
  SITE_REVIEW_DELETED_SUCCESS: 'SITE_REVIEW_DELETED_SUCCESS',
  REACTION_UPDATED_SUCCESS: 'REACTION_UPDATED_SUCCESS',
  COMMENT_DELETED_SUCCESS: 'COMMENT_DELETED_SUCCESS',
  BADGE_DELETED_SUCCESS: 'BADGE_DELETED_SUCCESS',
  BADGE_RESTORED_SUCCESS: 'BADGE_RESTORED_SUCCESS',
  BADGE_ASSIGNED_SUCCESS: 'BADGE_ASSIGNED_SUCCESS',
  BADGE_REMOVED_SUCCESS: 'BADGE_REMOVED_SUCCESS',
  TIER_CREATED_SUCCESS: 'TIER_CREATED_SUCCESS',
  TIER_UPDATED_SUCCESS: 'TIER_UPDATED_SUCCESS',
  TIER_DELETED_SUCCESS: 'TIER_DELETED_SUCCESS',
  TIER_RESTORED_SUCCESS: 'TIER_RESTORED_SUCCESS',
  CATEGORY_CREATED_SUCCESS: 'CATEGORY_CREATED_SUCCESS',
  CATEGORY_UPDATED_SUCCESS: 'CATEGORY_UPDATED_SUCCESS',
  CATEGORY_DELETED_SUCCESS: 'CATEGORY_DELETED_SUCCESS',
  CATEGORY_RESTORED_SUCCESS: 'CATEGORY_RESTORED_SUCCESS',
  POST_CREATED_SUCCESS: 'POST_CREATED_SUCCESS',
  POST_UPDATED_SUCCESS: 'POST_UPDATED_SUCCESS',
  POST_DELETED_SUCCESS: 'POST_DELETED_SUCCESS',
  REACTION_ADDED_SUCCESS: 'REACTION_ADDED_SUCCESS',
  REACTION_DELETED_SUCCESS: 'REACTION_DELETED_SUCCESS',
  COMMENT_ADDED_SUCCESS: 'COMMENT_ADDED_SUCCESS',
  USER_DELETED_SUCCESS: 'USER_DELETED_SUCCESS',
  OTP_SENT_SUCCESS: 'OTP_SENT_SUCCESS',
  GIFTCON_DELETED_SUCCESS: 'GIFTCON_DELETED_SUCCESS',
  EVENT_DELETED_SUCCESS: 'EVENT_DELETED_SUCCESS',
  OTP_GENERATED_SUCCESS: 'OTP_GENERATED_SUCCESS',
} as const;
